micronaut:
  application:
    name: demo
    
     
netty:
  default:
    allocator:
      max-order: 3

datasources:
        default:
          url: jdbc:postgresql://localhost:5432/micronaut
          driverClassName: org.postgresql.Driver
          username: postgres
          password: admin@123
          dialect: org.hibernate.dialect.PostgreSQLDialect
          schema-generate: update
          
  
jpa:
 default:
   properties:
     hibernate:
       hbm2ddl:
         auto: update
       show_sql: true  


        